openapi: 3.0.0
info:
  title: telemetry-manager-service-api
  description: Сервис управления телеметрией
  version: 0.1.0

tags:
  - name: telemetry
    description: Операции над телеметрией устройств

x-kusk:
  upstream:
    service:
      name: telemetry
      namespace: default
      port: 8082

paths:
  /device/{device_id}/telemetry:
    post:
      tags: [ telemetry ]
      description: Получение телеметрии за заданный период
      operationId: getTelemetryForPeriod
      parameters:
        - name: device_id
          required: true
          in: path
          description: "Идентификатор устройства"
          schema:
            type: number
            format: int64
      requestBody:
        description: "Входные данные для получения телеметрии за период"
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/TelemetryRequestDto'
      responses:
        '200':
          description: Телеметрия устройства за указанный период
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TelemetryArray'
  /device/{device_id}/telemetry/latest:
    get:
      tags: [ telemetry ]
      description: Получение последних показаний телеметрии устройства
      operationId: getLatestTelemetry
      parameters:
        - name: device_id
          required: true
          in: path
          description: "Идентификатор устройства"
          schema:
            type: number
            format: int64
      responses:
        '200':
          description: Последние данные телеметрии устройства
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TelemetryDto'
components:
  schemas:
    TelemetryDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 123
          description: Идентификатор записи телеметрии
        deviceId:
          type: integer
          format: int64
          example: 123
          description: Идентификатор устройства
        producedAt:
          type: string
          format: date-time
          example: "2021-01-30T08:30:00Z"
          description: Дата и время получения записи телеметрии
        telemetryUnit:
          type: string
          example: "Температура"
          description: Вид показания телеметрии
        data:
          type: string
          example: "30"
          description: Значение показания телеметрии
    TelemetryRequestDto:
      type: object
      properties:
        from:
          type: string
          format: date-time
          description: Дата и время начала диапазона для получения телеметрии
          example: "2021-01-30T08:30:00Z"
        to:
          type: string
          format: date-time
          description: Дата и время конца диапазона для получения телеметрии
          example: "2024-12-31T23:59:59Z"
    TelemetryArray:
      type: array
      items:
        $ref: '#/components/schemas/TelemetryDto'
